services:

  postgres_troyanov:
    image: postgres:17
    container_name: postgres_troyanov
    restart: always
    volumes:
      - postgres_troyanov_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  troyanov_test:
    image: troyanov_test
    build: ./
    container_name: troyanov_test
    restart: always
    depends_on:
      - postgres_troyanov
    env_file:
      - ./.env
    ports:
      - 7557:7557

volumes:
  postgres_troyanov_value:
