"""Initial revision

Revision ID: ef2774f170c7
Revises: 
Create Date: 2025-05-18 17:22:31.423317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2774f170c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=110), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_path'), 'activities', ['path'], unique=False)
    op.create_table('buildings',
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=8, scale=6), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='check_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='check_longitude_range'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_buildings_created_at'), 'buildings', ['created_at'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phones', sa.ARRAY(sa.String(length=15)), nullable=False),
    sa.Column('building_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_uuid'], ['buildings.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_table('company_activity',
    sa.Column('company_uuid', sa.UUID(), nullable=False),
    sa.Column('activity_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_uuid'], ['activities.uuid'], ),
    sa.ForeignKeyConstraint(['company_uuid'], ['companies.uuid'], ),
    sa.PrimaryKeyConstraint('company_uuid', 'activity_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_activity')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_buildings_created_at'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_activities_path'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
